apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okteto
  template:
    metadata:
      labels:
        app: okteto
    spec:
      containers:
      - image: okteto.dev/okteto:latest
        name: okteto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b0bd6fd7-db98-4f7d-b7cf-a6cc63c9ebfa"
        - name: Vless_Path
          value: "/b0bd6fd7-db98-4f7d-b7cf-a6cc63c9ebfa-vless"
        - name: Vmess_UUID
          value: "5a2ae306-33e4-42e3-8997-72f0e339ebab"
        - name: Vmess_Path
          value: "/5a2ae306-33e4-42e3-8997-72f0e339ebab-vmess"
        - name: Share_Path
          value: "/Share039"
